
title: Abigail Pickard's Homepage
page-top-title: Abigail Pickard
top-section-bg-text: Dr Abigail Pickard, Research Fellow
home-subtitle: Welcome
copyright-text: '&copy; Abigail Pickard 2025. All Rights Reserved.'
